### ISSUE TITLE
Indexing error (SOLR?): HTTP Error 500 

### ISSUE THREAD

**Issue by YoannMR** [opensemanticsearch/open-semantic-search#115]
Hi,

I'm having recurring issues when indexing (see error message below). This is temporarily fixed by restarting the SOLR server but it doesn't last long. I have indexed ~2 millions files so far.

Note that the error message only comes up when indexing a single file. When I index a folder, it doesn't complain and keep going through files while not indexing them (which delays error detection).

Could you please help me out?

```
Traceback (most recent call last):
  File "/usr/bin/opensemanticsearch-index-file", line 269, in <module>
    connector.commit()
  File "/usr/lib/python3/dist-packages/opensemanticetl/etl.py", line 280, in commit
    self.exporter.commit()
  File "/usr/lib/python3/dist-packages/opensemanticetl/export_solr.py", line 220, in commit
    request = urllib.request.urlopen( uri )
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Server Error
```

**Comment by YoannMR** [comment]
Turn out to be due to low hard drive space. It was fixed by increasing it.

Sorry about that!
