### ISSUE TITLE
Apache_Solr_HttpTransportException: '500' Status

### ISSUE THREAD

**Issue by FlorianReith** [opensemanticsearch/open-semantic-search#162]
Hey Guys,

iam running OSS on Ubuntu 16.10 (fresh install) with around 10.000 PDF files indexed.
Every time i manually stop and start solr or reboot the entire system i run into the following error on the /search/ page:

`Error:

Apache_Solr_HttpTransportException: '500' Status: Internal Server Error in /usr/share/solr-php-ui/Apache/Solr/Service.php:338 Stack trace: #0 /usr/share/solr-php-ui/Apache/Solr/Service.php(1170): Apache_Solr_Service->_sendRawGet('http://localhos...') #1 /usr/share/solr-php-ui/index.php(1399): Apache_Solr_Service->search('test', 0, 10, Array) #2 {main}`

as iam really new to oss i tried to find something in the solr log files and got this one:

`
2019-02-19 13:42:17.370 ERROR (qtp1582028874-55) [   ] o.a.s.s.HttpSolrCall null:org.apache.solr.core.SolrCoreInitializationException: SolrCore 'opensemanticsearch' is not available due to init failure: Failed to create new ManagedResource /schema/analysis/synonyms/skos of type org.apache.solr.rest.schema.analysis.ManagedSynonymGraphFilterFactory$SynonymManager due to: java.lang.IllegalArgumentException: term:  was completely eliminated by analyzer
        at org.apache.solr.core.CoreContainer.getCore(CoreContainer.java:1593)
        at org.apache.solr.servlet.HttpSolrCall.init(HttpSolrCall.java:249)
        at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:469)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:377)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:323)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:531)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.solr.common.SolrException: Failed to create new ManagedResource /schema/analysis/synonyms/skos of type org.apache.solr.rest.schema.analysis.ManagedSynonymGraphFilterFactory$SynonymManager due to: java.lang.IllegalArgumentException: term:  was completely eliminated by analyzer
        at org.apache.solr.core.SolrCore.<init>(SolrCore.java:1014)
        at org.apache.solr.core.SolrCore.<init>(SolrCore.java:869)
        at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1138)
        at org.apache.solr.core.CoreContainer.lambda$load$13(CoreContainer.java:684)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecutorService.java:197)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:209)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        ... 1 more
`

if i remove all packages and config files and reinstall them again from the deb file, everything works fine until the next reboot.

it would be great if someone could give me a hint or something helpfull.

thanks in advance :-)

**Comment by Mandalka** [comment]
After a reboot, does

/var/solr/data/opensemanticsearch/conf/_schema_analysis_synonyms_skos.json

exist?

If yes, which rights (ls -al) does the file have on the filesystem?

**Comment by botheredbybees** [comment]
having the same problem:
 
-rw-r----- 1 solr solr 44281 Sep 30 04:12 _schema_analysis_synonyms_skos.json

**Comment by pankus** [comment]
same problem here
