### ISSUE TITLE
install package in a brand new Ubuntu 16.4(AWS t3a.large 2CPU 8G) ERROR

### ISSUE THREAD

**Issue by StudyExchange** [opensemanticsearch/open-semantic-search#220]
install package in a brand new Ubuntu 16.4(AWS t3a.large 2CPU 8G) with below commands:
`sudo su root`
`cd`
`wget https://opensemanticsearch.org/download/open-semantic-search_19.12.18.deb`
`sudo apt-get update`
`sudo dpkg -i  open-semantic-search**.deb`
`sudo apt-get -f -y install`

got error:
Traceback (most recent call last):
  File "/var/lib/opensemanticsearch/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/lib/python3/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python3/dist-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/usr/lib/python3/dist-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/usr/lib/python3/dist-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/usr/lib/python3/dist-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/var/lib/opensemanticsearch/thesaurus/admin.py", line 12, in <module>
    from import_export import resources
  File "/usr/local/lib/python3.5/dist-packages/import_export/resources.py", line 5, in <module>
    import tablib
  File "/usr/local/lib/python3.5/dist-packages/tablib/__init__.py", line 4, in <module>
    from tablib.core import (
  File "/usr/local/lib/python3.5/dist-packages/tablib/core.py", line 16, in <module>
    from tablib import formats
  File "/usr/local/lib/python3.5/dist-packages/tablib/formats/__init__.py", line 12, in <module>
    from . import _xlsx as xlsx
  File "/usr/local/lib/python3.5/dist-packages/tablib/formats/_xlsx.py", line 9, in <module>
    import openpyxl
  File "/usr/local/lib/python3.5/dist-packages/openpyxl/__init__.py", line 6, in <module>
    from openpyxl.workbook import Workbook
  File "/usr/local/lib/python3.5/dist-packages/openpyxl/workbook/__init__.py", line 4, in <module>
    from .workbook import Workbook
  File "/usr/local/lib/python3.5/dist-packages/openpyxl/workbook/workbook.py", line 7, in <module>
    from openpyxl.worksheet.worksheet import Worksheet
  File "/usr/local/lib/python3.5/dist-packages/openpyxl/worksheet/worksheet.py", line 392
    return f"{get_column_letter(min_col)}{min_row}:{get_column_letter(max_col)}{max_row}"
                                                                                        ^
SyntaxError: invalid syntax
mkdir: cannot create directory ‘/var/opensemanticsearch’: File exists
mkdir: cannot create directory ‘/var/opensemanticsearch/media’: File exists
Traceback (most recent call last):
  File "/var/lib/opensemanticsearch/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/lib/python3/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python3/dist-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/usr/lib/python3/dist-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/usr/lib/python3/dist-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/usr/lib/python3/dist-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/var/lib/opensemanticsearch/thesaurus/admin.py", line 12, in <module>
    from import_export import resources
  File "/usr/local/lib/python3.5/dist-packages/import_export/resources.py", line 5, in <module>
    import tablib
  File "/usr/local/lib/python3.5/dist-packages/tablib/__init__.py", line 4, in <module>
    from tablib.core import (
  File "/usr/local/lib/python3.5/dist-packages/tablib/core.py", line 16, in <module>
    from tablib import formats
  File "/usr/local/lib/python3.5/dist-packages/tablib/formats/__init__.py", line 12, in <module>
    from . import _xlsx as xlsx
  File "/usr/local/lib/python3.5/dist-packages/tablib/formats/_xlsx.py", line 9, in <module>
    import openpyxl
  File "/usr/local/lib/python3.5/dist-packages/openpyxl/__init__.py", line 6, in <module>
    from openpyxl.workbook import Workbook
  File "/usr/local/lib/python3.5/dist-packages/openpyxl/workbook/__init__.py", line 4, in <module>
    from .workbook import Workbook
  File "/usr/local/lib/python3.5/dist-packages/openpyxl/workbook/workbook.py", line 7, in <module>
    from openpyxl.worksheet.worksheet import Worksheet
  File "/usr/local/lib/python3.5/dist-packages/openpyxl/worksheet/worksheet.py", line 392
    return f"{get_column_letter(min_col)}{min_row}:{get_column_letter(max_col)}{max_row}"
                                                                                        ^
SyntaxError: invalid syntax
chown: cannot access '/var/opensemanticsearch/db/db.sqlite3': No such file or directory
chmod: cannot access '/var/opensemanticsearch/db/db.sqlite3': No such file or directory
Module wsgi already enabled
Traceback (most recent call last):
  File "/var/lib/opensemanticsearch/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/lib/python3/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python3/dist-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/usr/lib/python3/dist-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/usr/lib/python3/dist-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/usr/lib/python3/dist-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/var/lib/opensemanticsearch/thesaurus/admin.py", line 12, in <module>
    from import_export import resources
  File "/usr/local/lib/python3.5/dist-packages/import_export/resources.py", line 5, in <module>
    import tablib
  File "/usr/local/lib/python3.5/dist-packages/tablib/__init__.py", line 4, in <module>
    from tablib.core import (
  File "/usr/local/lib/python3.5/dist-packages/tablib/core.py", line 16, in <module>
    from tablib import formats
  File "/usr/local/lib/python3.5/dist-packages/tablib/formats/__init__.py", line 12, in <module>
    from . import _xlsx as xlsx
  File "/usr/local/lib/python3.5/dist-packages/tablib/formats/_xlsx.py", line 9, in <module>
    import openpyxl
  File "/usr/local/lib/python3.5/dist-packages/openpyxl/__init__.py", line 6, in <module>
    from openpyxl.workbook import Workbook
  File "/usr/local/lib/python3.5/dist-packages/openpyxl/workbook/__init__.py", line 4, in <module>
    from .workbook import Workbook
  File "/usr/local/lib/python3.5/dist-packages/openpyxl/workbook/workbook.py", line 7, in <module>
    from openpyxl.worksheet.worksheet import Worksheet
  File "/usr/local/lib/python3.5/dist-packages/openpyxl/worksheet/worksheet.py", line 392
    return f"{get_column_letter(min_col)}{min_row}:{get_column_letter(max_col)}{max_row}"
                                                                                        ^
SyntaxError: invalid syntax
Setting up qt-at-spi:amd64 (0.4.0-3) ...
Processing triggers for libc-bin (2.23-0ubuntu11) ...
Processing triggers for ureadahead (0.100.0-19.1) ...
Processing triggers for systemd (229-4ubuntu21.22) ...
Processing triggers for ufw (0.35-0ubuntu2) ...
Processing triggers for libapache2-mod-php7.0 (7.0.33-0ubuntu0.16.04.7) ...
Processing triggers for dictionaries-common (1.26.3) ...
Processing triggers for ca-certificates (20170717~16.04.2) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

done.
done.

**Comment by StudyExchange** [comment]
Install package in a brand new Ubuntu 18.04(AWS t3a.large 2CPU 8G)  with [open-semantic-search_19.12.18.deb](https://opensemanticsearch.org/download/open-semantic-search_19.12.18.deb) work.
