### ISSUE TITLE
Building docker image fails

### ISSUE THREAD

**Issue by skoulouzis** [opensemanticsearch/open-semantic-search#287]
Steps I followed to build:

git clone https://github.com/opensemanticsearch/open-semantic-search.git
git submodule init
git submodule update
docker build ./

Error:
Step 31/49 : RUN python3 /var/lib/opensemanticsearch/manage.py migrate
 ---> Running in 63cd25732360
Traceback (most recent call last):
  File "/var/lib/opensemanticsearch/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 327, in execute
    self.check()
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/lib/python3/dist-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/lib/python3/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/lib/python3/dist-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/lib/python3/dist-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/usr/lib/python3/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib/python3/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/lib/opensemanticsearch/opensemanticsearch/urls.py", line 7, in <module>
    from django.urls import path
ImportError: cannot import name 'path' from 'django.urls' (/usr/lib/python3/dist-packages/django/urls/__init__.py)
The command '/bin/sh -c python3 /var/lib/opensemanticsearch/manage.py migrate' returned a non-zero code: 1

**Comment by c4seyla** [comment]
@skoulouzis the django version installed in the Dockerfile python3-django is 1.14 which doesn't have support for urls as this was added in 2+
Add this line above the other pip3 install 
RUN pip3 install --no-cache-dir Django==2.0
RUN pip3 install --no-cache-dir django-import-export==1.2.0
And delete the line python3-django \

**Comment by Mandalka** [comment]
New release should resolve that for master branch (which is ahead of Debian stable to support fueature releases) by https://github.com/opensemanticsearch/open-semantic-search/issues/303

**Comment by Mandalka** [comment]
I close this ticket, because this issue solved by switching master branch to current ubuntu lts, which yet includes django 2 and such error on next linuxdistribution upgrades will be automatically detected by the new debian and ubuntu integration tests.

But seems yet some other upgrade problems before fix tomorrow or next days (first upgrade-issues of the docker container detected by additional automated integration tests) due heavy upgrade/dependency hell work and restructure / improvement of CI/CD helping on development of new features and next dependency libs/debian/ubuntu upgrades.

**Comment by Mandalka** [comment]
BTW: Maybe important to clone the repo recursive since not only this repo has submodules, but some submodules have submodules, too.
