### ISSUE TITLE
Import Annotations from Hypothesis Errors

### ISSUE THREAD

**Issue by jazzdup** [opensemanticsearch/open-semantic-search#346]
Importing annotations filtered by user causes following error:
(as an aside, filtered by group appears not to work)
./solr.log.9-4029-2021-02-19 16:47:01.876 DEBUG (qtp1893960929-16) [   x:opensemanticsearch] o.a.s.u.p.AllValuesOrNoneFieldMutatingUpdateProcessor field 'etl_enhance_multilingual_b' HashMap value '{add-distinct=true}' is not mutable, so no values will be mutated
./solr.log.9-4030-2021-02-19 16:47:01.876 DEBUG (qtp1893960929-16) [   x:opensemanticsearch] o.a.s.u.p.AddSchemaFieldsUpdateProcessorFactory No fields or copyFields to add to the schema.
./solr.log.9-4031-2021-02-19 16:47:01.876 DEBUG (qtp1893960929-16) [   x:opensemanticsearch] o.a.s.u.p.LogUpdateProcessorFactory PRE_UPDATE add{,id=https://hypothes.is/welcome/6f5036dd7adda788} {{params(df=_text_),defaults(wt=json)}}
./solr.log.9-4032-2021-02-19 16:47:01.876 DEBUG (qtp1893960929-16) [   x:opensemanticsearch] o.a.s.u.p.LogUpdateProcessorFactory PRE_UPDATE FINISH {{params(df=_text_),defaults(wt=json)}}
./solr.log.9-4033-2021-02-19 16:47:01.876 INFO  (qtp1893960929-16) [   x:opensemanticsearch] o.a.s.u.p.LogUpdateProcessorFactory [opensemanticsearch]  webapp=/solr path=/update params={}{} 0 1
./solr.log.9:4034:2021-02-19 16:47:01.876 ERROR (qtp1893960929-16) [   x:opensemanticsearch] o.a.s.h.RequestHandlerBase org.apache.solr.common.SolrException: **ERROR: [doc=https://hypothes.is/welcome/6f5036dd7adda788] multiple values encountered for non multiValued field etl_enhance_multilingual_time_millis_i: [1, 0]**
./solr.log.9-4035-	at org.apache.solr.update.DocumentBuilder.toDocument(DocumentBuilder.java:153)
./solr.log.9-4036-	at org.apache.solr.update.AddUpdateCommand.getLuceneDocument(AddUpdateCommand.java:102)

**Comment by jazzdup** [comment]
not easily reproducible, will repost with test case if needed but probably easiest workaround is to omit enhance_multilingual plugin as not needed for me

**Comment by jazzdup** [comment]
also seeing this error when adding an new annotation, enhance_multilingual plugin seems to cause this problem in etl.py used by various django webapps

**Comment by jazzdup** [comment]
after clearing solr data completely and reloading docs, this error no longer occurs on 1 out of 2 opensemanticsearch instances I have, I haven't yet tested the other one. 
The field is not multivalued, anyway regular annotations (notes field) are now being saved to solr. (Although another bug is that they aren't searchable which is the opposite of what the large font in the UI says but that's another issue. Unless that field requires a re-index before it's searchable again perhaps?)
