### ISSUE TITLE
Unable to use opensemanticsearch-delete for file with special characters

### ISSUE THREAD

**Issue by RafaelReder** [opensemanticsearch/open-semantic-search#349]
When tyring to delete a file from an index using opensemanticsearch-delete it fails with file names containing special characters.

Traceback (most recent call last):
  File "/usr/bin/opensemanticsearch-delete", line 115, in <module>
    connector.delete(uri)
  File "/usr/bin/opensemanticsearch-delete", line 60, in delete
    self.connector.delete(parameters=self.config, docid=uri)
  File "/usr/lib/python3/dist-packages/opensemanticetl/export_solr.py", line 347, in delete
    result = solr.delete(id=docid)
  File "/usr/lib/python3/dist-packages/pysolr.py", line 960, in delete
    return self._update(m, commit=commit, softCommit=softCommit, waitFlush=waitFlush, waitSearcher=waitSearcher, handler=handler)
  File "/usr/lib/python3/dist-packages/pysolr.py", line 500, in _update
    return self._send_request('post', path, message, {'Content-type': 'text/xml; charset=utf-8'})
  File "/usr/lib/python3/dist-packages/pysolr.py", line 412, in _send_request
    raise SolrError(error_message % (resp.status_code, solr_message))
pysolr.SolrError: Solr responded with an error (HTTP 500): [Reason: [com.ctc.wstx.exc.WstxLazyException] Unexpected character ' ' (code 32) (missing name?)
 at [row,col {unknown-source}]: [1,65]]

When trying to URL encode the spaces and special characters it does not delete the file from the index as well

**Comment by RafaelReder** [comment]
I noticed that the ampersand needs to be escaped with &amp; it is working now. closing this
