### ISSUE TITLE
Starting Scrapy crawler process in Celery task fails

### ISSUE THREAD

**Issue by Mandalka** [opensemanticsearch/open-semantic-search#67]
Starting a Scrapy crawler by Celery task in Web UI works only few times, after some runs:

[ERROR/MainProcess] Task etl.index_web_crawl[5c141224-101e-41f9-8053-6d908aa62bc2] raised unexpected: ReactorNotRestartable()
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/bin/etl_tasks", line 76, in index_web_crawl
    result = connector_web_crawl.index(uri, crawler_type)
  File "/usr/lib/python3/dist-packages/opensemanticetl/etl_web_crawl.py", line 83, in index
    process.start() # the script will block here until the crawling is finished
  File "/usr/local/lib/python3.5/dist-packages/scrapy/crawler.py", line 285, in start
    reactor.run(installSignalHandlers=False)  # blocking call
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/base.py", line 1242, in run
    self.startRunning(installSignalHandlers=installSignalHandlers)
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/base.py", line 1222, in startRunning
    ReactorBase.startRunning(self)
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/base.py", line 730, in startRunning
    raise error.ReactorNotRestartable()
twisted.internet.error.ReactorNotRestartable

**Comment by Mandalka** [comment]
The Twisted reactor used by Scrapy could only be started once per process/worker (we had as many workers as processors).

I limited the maximal Celery tasks for every worker to one, so no worker will init a reactor more than one time in the same process.
